services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Création d'un root admin pour l'instance (change les valeurs dans .env)
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db
      - ./mongo/initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "27017:27017"
    networks:
      - appnet

  app:
    build: .
    image: tarpinfur-back:latest
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATA_MONGODB_HOST=${MONGO_HOST}
      - SPRING_DATA_MONGODB_PORT=${MONGO_PORT}
      - SPRING_DATA_MONGODB_DATABASE=${MONGO_DATABASE}
      - SPRING_DATA_MONGODB_USERNAME=${MONGO_USERNAME}
      - SPRING_DATA_MONGODB_PASSWORD=${MONGO_PASSWORD}
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=${MONGO_AUTH_DATABASE}
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI:-mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:${MONGO_PORT}/${MONGO_DATABASE}?authSource=${MONGO_AUTH_DATABASE}}
      - SERVER_PORT=${SERVER_PORT:-8080}
    networks:
      - appnet
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  appnet:
    driver: bridge